//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Form_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgi
    {
        public int KullaniciNO { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Bolum { get; set; }
    }
}
